server:
  port: 8001

spring:
  application:
    name: server-a
  # 链路监控
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
      base-url: http://192.168.99.100:9411/ # 指定了 Zipkin 服务器的地址

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# 开启服务熔断
feign:
  hystrix:
    enabled: true